#!/usr/bin/env python
"""
Migration utility to convert Alpaca configuration to Coinbase.

This script helps users migrate from Alpaca to Coinbase by:
1. Converting environment variables from .env file
2. Mapping trading parameters from Alpaca to Coinbase
3. Validating the Coinbase configuration
4. Creating a backup of the original configuration

Usage:
    python tools/alpaca_to_coinbase_migration.py [options]

Options:
    --input-env PATH       Path to input .env file (default: .env)
    --output-env PATH      Path to output .env file (default: .env.coinbase)
    --apply                Apply changes to the original .env file
    --validate-only        Only validate the Coinbase configuration without making changes
    --sandbox              Configure for Coinbase sandbox environment
"""
import os
import sys
import argparse
import shutil
from datetime import datetime
from typing import Dict, Tuple, Optional, List

# Add the parent directory to the path so we can import the bot package
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    from bot.config import Config, CoinbaseCredentials
    from bot.utils import log_info, log_error, log_warning
except ImportError:
    print("Error: Could not import required modules from the bot package.")
    print("Make sure you're running this script from the project root directory.")
    sys.exit(1)


def parse_arguments() -> argparse.Namespace:
    """
    Parse command line arguments.
    
    Returns:
        Namespace containing the parsed arguments
    """
    parser = argparse.ArgumentParser(description="Migrate from Alpaca to Coinbase configuration")
    
    parser.add_argument(
        "--input-env",
        type=str,
        default=".env",
        help="Path to input .env file (default: .env)"
    )
    
    parser.add_argument(
        "--output-env",
        type=str,
        default=".env.coinbase",
        help="Path to output .env file (default: .env.coinbase)"
    )
    
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply changes to the original .env file"
    )
    
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Only validate the Coinbase configuration without making changes"
    )
    
    parser.add_argument(
        "--sandbox",
        action="store_true",
        help="Configure for Coinbase sandbox environment"
    )
    
    return parser.parse_args()


def read_env_file(file_path: str) -> Dict[str, str]:
    """
    Read environment variables from a .env file.
    
    Args:
        file_path: Path to the .env file
        
    Returns:
        Dictionary of environment variables
    """
    env_vars = {}
    
    try:
        with open(file_path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                    
                if '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    except FileNotFoundError:
        log_error(f"Environment file not found: {file_path}")
    except Exception as e:
        log_error(f"Error reading environment file: {str(e)}")
        
    return env_vars


def write_env_file(file_path: str, env_vars: Dict[str, str]) -> bool:
    """
    Write environment variables to a .env file.
    
    Args:
        file_path: Path to the .env file
        env_vars: Dictionary of environment variables
        
    Returns:
        True if successful, False otherwise
    """
    try:
        with open(file_path, 'w') as f:
            f.write("# Environment variables for crypto trading bot\n")
            f.write("# Generated by alpaca_to_coinbase_migration.py\n")
            f.write(f"# Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            
            # Write Alpaca variables as comments
            if any(key.startswith("ALPACA_") for key in env_vars):
                f.write("# Alpaca API credentials (commented out)\n")
                for key, value in env_vars.items():
                    if key.startswith("ALPACA_") or key == "IS_PAPER_TRADING":
                        f.write(f"# {key}={value}\n")
                f.write("\n")
            
            # Write Coinbase variables
            f.write("# Coinbase Advanced Trade API credentials\n")
            for key, value in env_vars.items():
                if key.startswith("COINBASE_"):
                    f.write(f"{key}={value}\n")
            
            # Add any other variables that aren't related to API credentials
            f.write("\n# Other configuration variables\n")
            for key, value in env_vars.items():
                if not key.startswith("ALPACA_") and not key.startswith("COINBASE_") and key != "IS_PAPER_TRADING":
                    f.write(f"{key}={value}\n")
                    
        return True
    except Exception as e:
        log_error(f"Error writing environment file: {str(e)}")
        return False


def create_backup(file_path: str) -> bool:
    """
    Create a backup of a file.
    
    Args:
        file_path: Path to the file to backup
        
    Returns:
        True if successful, False otherwise
    """
    backup_path = f"{file_path}.bak.{datetime.now().strftime('%Y%m%d%H%M%S')}"
    try:
        shutil.copy2(file_path, backup_path)
        log_info(f"Created backup of {file_path} at {backup_path}")
        return True
    except Exception as e:
        log_error(f"Error creating backup: {str(e)}")
        return False


def convert_alpaca_to_coinbase(env_vars: Dict[str, str], use_sandbox: bool) -> Dict[str, str]:
    """
    Convert Alpaca environment variables to Coinbase.
    
    Args:
        env_vars: Dictionary of environment variables
        use_sandbox: Whether to use Coinbase sandbox environment
        
    Returns:
        Updated dictionary of environment variables
    """
    # Create a copy of the original environment variables
    new_env_vars = env_vars.copy()
    
    # Check if Coinbase credentials already exist
    has_coinbase_credentials = all(key in env_vars for key in [
        "COINBASE_API_KEY", 
        "COINBASE_API_SECRET", 
        "COINBASE_PASSPHRASE"
    ])
    
    # If Coinbase credentials don't exist, add placeholders
    if not has_coinbase_credentials:
        new_env_vars["COINBASE_API_KEY"] = "your_coinbase_api_key_here"
        new_env_vars["COINBASE_API_SECRET"] = "your_coinbase_api_secret_here"
        new_env_vars["COINBASE_PASSPHRASE"] = "your_coinbase_passphrase_here"
    
    # Set sandbox mode
    new_env_vars["COINBASE_SANDBOX"] = "True" if use_sandbox else "False"
    
    # Map IS_PAPER_TRADING to COINBASE_SANDBOX if not explicitly set
    if "IS_PAPER_TRADING" in env_vars and "COINBASE_SANDBOX" not in env_vars:
        is_paper = env_vars["IS_PAPER_TRADING"].lower() in ("true", "1", "t", "yes")
        new_env_vars["COINBASE_SANDBOX"] = "True" if is_paper else "False"
    
    return new_env_vars


def validate_coinbase_config(env_vars: Dict[str, str]) -> Tuple[bool, List[str]]:
    """
    Validate Coinbase configuration.
    
    Args:
        env_vars: Dictionary of environment variables
        
    Returns:
        Tuple of (is_valid, error_messages)
    """
    errors = []
    
    # Check if required Coinbase variables exist
    required_vars = ["COINBASE_API_KEY", "COINBASE_API_SECRET", "COINBASE_PASSPHRASE"]
    missing_vars = [var for var in required_vars if var not in env_vars]
    
    if missing_vars:
        errors.append(f"Missing required Coinbase variables: {', '.join(missing_vars)}")
    
    # Check if variables have placeholder values
    placeholder_vars = []
    for var in required_vars:
        if var in env_vars and (
            env_vars[var] == "your_coinbase_api_key_here" or
            env_vars[var] == "your_coinbase_api_secret_here" or
            env_vars[var] == "your_coinbase_passphrase_here"
        ):
            placeholder_vars.append(var)
    
    if placeholder_vars:
        errors.append(f"The following variables have placeholder values: {', '.join(placeholder_vars)}")
    
    # Check if COINBASE_SANDBOX is set correctly
    if "COINBASE_SANDBOX" in env_vars:
        sandbox_value = env_vars["COINBASE_SANDBOX"].lower()
        if sandbox_value not in ("true", "false", "1", "0", "t", "f"):
            errors.append(f"Invalid value for COINBASE_SANDBOX: {env_vars['COINBASE_SANDBOX']}. Must be True or False.")
    
    return len(errors) == 0, errors


def main() -> int:
    """
    Main entry point for the migration utility.
    
    Returns:
        Exit code (0 for success, non-zero for error)
    """
    args = parse_arguments()
    
    # Read input environment file
    env_vars = read_env_file(args.input_env)
    if not env_vars:
        log_error(f"No environment variables found in {args.input_env}")
        return 1
    
    # If validate-only, check if Coinbase configuration is valid
    if args.validate_only:
        is_valid, errors = validate_coinbase_config(env_vars)
        if is_valid:
            log_info("Coinbase configuration is valid.")
            return 0
        else:
            log_error("Coinbase configuration is invalid:")
            for error in errors:
                log_error(f"  - {error}")
            return 1
    
    # Convert Alpaca to Coinbase
    new_env_vars = convert_alpaca_to_coinbase(env_vars, args.sandbox)
    
    # Validate the new configuration
    is_valid, errors = validate_coinbase_config(new_env_vars)
    if not is_valid:
        log_warning("Generated Coinbase configuration has issues:")
        for error in errors:
            log_warning(f"  - {error}")
        log_warning("You will need to update these values manually.")
    
    # Write output environment file
    output_path = args.input_env if args.apply else args.output_env
    
    # Create backup if applying changes to the original file
    if args.apply and os.path.exists(args.input_env):
        if not create_backup(args.input_env):
            log_error("Failed to create backup, aborting.")
            return 1
    
    # Write the new environment file
    if write_env_file(output_path, new_env_vars):
        if args.apply:
            log_info(f"Successfully updated {output_path} with Coinbase configuration.")
        else:
            log_info(f"Successfully wrote Coinbase configuration to {output_path}.")
        
        if not is_valid:
            log_warning(f"Please update the placeholder values in {output_path} before using.")
        
        return 0
    else:
        log_error(f"Failed to write configuration to {output_path}.")
        return 1


if __name__ == "__main__":
    sys.exit(main())